name: Get Changed Packages
description: Get all of the packages with changed/modified files in a pull request or push's commits.
author: Misha Serenkov | Jitterbit, Inc.
branding:
  icon: file
  color: purple
runs:
  using: node12
  main: dist/index.js
inputs:
  token:
    description: >
      GitHub token for GitHub API requests.
      Users shouldn't need to set this themselves.
    required: true
    default: ${{ github.token }}
  packageFolders:
    description: >
      List of folders with packages.
      Can be JSON string.
    required: false
  format:
    description: >
      Format of the steps output context.
      Can be 'space-delimited', 'csv', or 'json'.
    required: true
    default: json
outputs:
  folders:
    description: >
      Array of paths to changed packages.
